version: '3.8'
services:
  postgres_dev:
    image: postgres:15-alpine
    container_name: skyner_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: skyner_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15-alpine
    container_name: skyner_test
    restart: unless-stopped
    environment:
      POSTGRES_DB: skyner_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: skyner_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_dev_data:
  postgres_test_data:
  redis_data:
