/**
 * Codes d'erreur structurés par domaine
 * Format: DOMAIN_SPECIFIC_ERROR
 */
export const ERROR_CODES = {
  // Auth (1000-1999)
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_PASSWORD_RESET_TOKEN_INVALID: 'AUTH_PASSWORD_RESET_TOKEN_INVALID',
  AUTH_PASSWORD_RESET_TOKEN_EXPIRED: 'AUTH_PASSWORD_RESET_TOKEN_EXPIRED',
  AUTH_PASSWORD_RESET_TOKEN_USED: 'AUTH_PASSWORD_RESET_TOKEN_USED',

  // Users (2000-2999)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_INVALID_CREDENTIALS: 'USER_INVALID_CREDENTIALS',
  USER_ACCOUNT_DISABLED: 'USER_ACCOUNT_DISABLED',

  // Organizations (3000-3999)
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_USER_NOT_MEMBER: 'ORG_USER_NOT_MEMBER',
  ORG_USER_ALREADY_MEMBER: 'ORG_USER_ALREADY_MEMBER',
  ORG_INSUFFICIENT_ROLE: 'ORG_INSUFFICIENT_ROLE',
  ORG_SLUG_ALREADY_EXISTS: 'ORG_SLUG_ALREADY_EXISTS',

  // Sessions (4000-4999)
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_NOT_OWNED: 'SESSION_NOT_OWNED',

  // Validation (9000-9999)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID: 'VALIDATION_FIELD_INVALID',

  // System (10000+)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES]